### ISSUE TITLE
Estimation of `pred_sample_direction`

### ISSUE THREAD

**Issue by markub3327** [inbarhub/DDPM_inversion#12]
Hi @inbarhub @fallenshock

   I see you use a different equation for the estimation of pred_sample_direction as was in the original DDIM paper:

    # 6. compute "direction pointing to x_t" of formula (12) from https://arxiv.org/pdf/2010.02502.pdf
    # pred_sample_direction = (1 - alpha_prod_t_prev - std_dev_t**2) ** (0.5) * model_output_direction
    pred_sample_direction = (1 - alpha_prod_t_prev - eta * variance) ** (0.5) * model_output_direction

If i tried it compare numerically there is a significant difference:
```python
import numpy as np

x = np.random.rand(10)
y = np.random.normal(0, 1, 10)
variance = np.random.rand(10)
eta = 0.5
std_dev_t = eta * variance ** (0.5)

a = (x - eta * variance) ** (0.5) * y
b = (x - std_dev_t**2) ** (0.5) * y

print(a)
print(b)

np.testing.assert_allclose(a, b)
```

## Result
Mismatched elements: 10 / 10 (100%)
Max absolute difference: 0.37401943
Max relative difference: 0.39348061
 x: array([ 0.044005, -0.215482, -0.025475,  0.006714,  0.608389,  0.508254,
       -0.111491,  0.481015, -0.558999, -0.92056 ])
 y: array([ 0.072554, -0.217981, -0.026114,  0.007178,  0.677106,  0.515384,
       -0.153175,  0.505885, -0.603202, -1.294579])

Is there any proof for this change? Do I have an issue with my test code, I substituted a lot of original code.

I think the correct one will be:
    pred_sample_direction = (1 - alpha_prod_t_prev - (eta**2) * variance) ** (0.5) * model_output_direction

Thanks for the explanation.

**Comment by inbarhub** [comment]
Hi, in our code eta=1, so the only different is between `variance` and `std_dev_t**2`, which theoretically should be equivalent. If you want the code to also handle cases where eta != 1, you would need to multiply `std_dev_t**2` by eta:
`pred_sample_direction = (1 - alpha_prod_t_prev - eta * std_dev_t**2) ** (0.5) * model_output_direction`

**Comment by x2x5** [comment]
Hi, is it a typo in your paper on page 4?
![image](https://github.com/user-attachments/assets/38c104c3-fad7-41bf-9ea8-9bf05576e973)

because in DDIM sigma_t should be:

![image](https://github.com/user-attachments/assets/b9ef32a9-4ab2-4972-8a7a-056d4188ef28)

so it should not be beta_t, it should be (1-alpha_t/alpha_t_prev), right?

and the eta should be eta^2，right?

**Comment by fangxuehouwuming** [comment]
> Hi, is it a typo in your paper on page 4? ![image](https://github.com/user-attachments/assets/38c104c3-fad7-41bf-9ea8-9bf05576e973)
> 
> because in DDIM sigma_t should be:
> 
> ![image](https://github.com/user-attachments/assets/b9ef32a9-4ab2-4972-8a7a-056d4188ef28)
> 
> so it should not be beta_t, it should be (1-alpha_t/alpha_t_prev), right?
> 
> and the eta should be eta^2，right?

hello, have you solved this problem? I'm confused about the formula.
