### ISSUE TITLE
Why z1 = 0 in DDPM?

### ISSUE THREAD

**Issue by lihuining** [inbarhub/DDPM_inversion#13]
Hello, I used your code for a list of frames, but I found that the inversion and reconstruction of the last frame are very poor. I noticed that in the code, the last item of zs in the inversion_forward_process function is forced to be zero. I don't understand why this operation is used, as it only generates a very blurry image.
![image](https://github.com/user-attachments/assets/4d86ec35-a485-4600-bebe-e689d8d479cc)

**Comment by inbarhub** [comment]
Hi, since there is no `z` between `x_1` and `x_0`, we define it as zeros. I agree that to achieve a perfect reconstruction, especially when the number of steps is small you could (or should) include `z_1` as well.
