### ISSUE TITLE
why noise maps should be statistically independent and have a standard normal distribution?

### ISSUE THREAD

**Issue by maxin-cn** [inbarhub/DDPM_inversion#14]
Thank you so much for your wonderful work and for open-sourcing the relevant code. I would like to inquire that why should noise maps be statistically independent and follow a standard normal distribution?
![image](https://github.com/user-attachments/assets/ab476911-3fed-470f-9499-03c4e1ca3303)

**Comment by inbarhub** [comment]
Hi, thanks!

The noise maps used in DDPM sampling are statistically independent and follow a normal distribution. However, when dealing with real images, if we attempt to find the noise maps that generated a given image, we might assume they would also be statistically independent and normally distributed. In our case, we found that this assumption does not hold true.
