### ISSUE TITLE
Question about error accumulation

### ISSUE THREAD

**Issue by BossunWang** [inbarhub/DDPM_inversion#2]
Hi expert,
Nice work and get key point about inversion with independent random noises.
But I can't understand which case of error accumulation could be affect zt and xt-1 in algorithm 1.
May you give me some examples about this?

**Comment by inbarhub** [comment]
Hi, the error comes from a floating point precision when dividing by 'sigma'. We can either not divide by sigma (and then store sigma times Z) or divide by sigma and do the step you mention.

**Comment by x2x5** [comment]
> Hi, the error comes from a floating point precision when dividing by 'sigma'. We can either not divide by sigma (and then store sigma times Z) or divide by sigma and do the step you mention.
<img width="513" alt="image" src="https://github.com/user-attachments/assets/686d0dbe-ac41-45ff-a874-74884d13e366" />

Hi, I'm still really confused why x_{t-1} can change?  Isn't it merely an equation transformation?
