### ISSUE TITLE
Dependence between epsilons

### ISSUE THREAD

**Issue by josejhlee** [inbarhub/DDPM_inversion#5]
Hi authors,
I fail to understand why the randomly sampled epsilons are dependent in respect to the timestep axis. And likewise, I fail to understand why does epsilon_hat is independent. Thank you for the great work and eager for your reply!

**Comment by inbarhub** [comment]
Hi, 

Eq1 establishes a connection between `x_t` and `x_{t-1}`, incorporating independent noise (eta).  Upon rephrasing it as Eq2, we depict a connection from `x_0` to `x_t` leading to a noise (epsilon) that takes into account all preceding etas from Eq 1.
Consequently, the epsilon linking `x_0` to `x_{t-1}` demonstrates a significant correlation with the epsilon linking `x_0` to `x_t`. These epsilons lack independence.

However, in our scenario, the sampling process generating `x_t` was devised as a separate auxiliary process between all timesteps.  There exists no connection between the creation of  `x_t` and the creation of `x_{t-1}`. This suggests that the epsilons creating `x_t` are independent across all timesteps.
