### ISSUE TITLE
Asyrp Integration

### ISSUE THREAD

**Issue by sidney1505** [inbarhub/DDPM_inversion#6]
Hi,

first thank you for your amazing work, it is straightforward to get it working!

However, one question, in line https://github.com/inbarhub/DDPM_inversion/blob/6b7344824449f56c667e953b3956a82960e49475/ddm_inversion/inversion_utils.py#L220 you mention Asyrp which is probably a reference to https://github.com/kwonminki/Asyrp_official - why is Asyrp not mentioned in your paper and why is the flag not used? I would love to integrate Asyrp with your work, but I have a hard time making Asyrp work.

Best,
Sidney

**Comment by inbarhub** [comment]
Hi,

We've incorporated it, though it hasn't been included in this paper. Integrating Asyrp can be seamlessly accomplished by retrieving the h_space from the UNET along with the inversion process.
