### ISSUE TITLE
SDXL or SDXL turo

### ISSUE THREAD

**Issue by betterze** [inbarhub/DDPM_inversion#7]
Dear @inbarhub ,

Thank you for sharing this great work. 

Is there a way to make this repo support sdxl or sdxl turbo?

I appreciate your help.

Best Wishes,
Zongze

**Comment by inbarhub** [comment]
Hi,

Our method is adaptable for integration with the sdxl model, although we did not incorporate it into our implementation. It's worth noting that [ConsiStory](https://arxiv.org/pdf/2402.03286.pdf) paper and [LEDITS++](https://arxiv.org/pdf/2311.16711.pdf) use our approach with the sdxl model.

**Comment by betterze** [comment]
thx a lot
