### ISSUE TITLE
imagenet-r-ti2i source prompt

### ISSUE THREAD

**Issue by wentaohu1208** [inbarhub/DDPM_inversion#9]
It seems that there is no source prompt in imagenet-r-ti2i for most real images. 
```python
  -
    init_img:  /ImageNetR-TI2I/cat/cartoon_0.jpg
 
    target_prompts:
    - a sculpture of a cat
    - a graffiti of a cat
    - an embroidery of a cat
    - an image of a bear
    - an origami of a dog
``` 
Does this mean I need use the category and style shown in 'init_img' to create src_prompt by myself? for example, I create 'a cartoon of a cat' for this init_img

**Comment by inbarhub** [comment]
Hi, Yes. In case there was no source prompt we gave it as you described.
